CREATE TYPE "PlanningRhProfile" AS ENUM (
  'WITH_RTT_VARIABLE_1',
  'WITH_RTT_VARIABLE_2',
  'WITH_RTT_FIXED',
  'WITH_RTT_NIGHT',
  'WITH_RTT_FORFAIT_JOUR',
  'WITHOUT_RTT_VARIABLE_1',
  'WITHOUT_RTT_VARIABLE_2',
  'WITHOUT_RTT_FIXED'
);

ALTER TABLE "User"
ADD COLUMN "planningRhProfile" "PlanningRhProfile" NOT NULL DEFAULT 'WITH_RTT_VARIABLE_1';
